- name: Install apache in file_servers
  hosts: file_servers
  become: yes
  roles:
    - file_servers
  tags: apache2

- name: Install mariadb in db_servers
  hosts: db_servers
  become: yes
  roles:
    - db_servers
  tags: db

- name: Install samba in web_servers
  hosts: web_servers
  become: yes
  roles:
    - web_servers
  tags: samba
